// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: internal/extensions/extension.proto

package extensions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_extensions_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_extensions_extension_proto_rawDescGZIP(), []int{0}
}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_internal_extensions_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_internal_extensions_extension_proto_rawDescGZIP(), []int{1}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VariableList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     []*Variable            `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableList) Reset() {
	*x = VariableList{}
	mi := &file_internal_extensions_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableList) ProtoMessage() {}

func (x *VariableList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableList.ProtoReflect.Descriptor instead.
func (*VariableList) Descriptor() ([]byte, []int) {
	return file_internal_extensions_extension_proto_rawDescGZIP(), []int{2}
}

func (x *VariableList) GetVariables() []*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type MethodNameList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []string               `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodNameList) Reset() {
	*x = MethodNameList{}
	mi := &file_internal_extensions_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodNameList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodNameList) ProtoMessage() {}

func (x *MethodNameList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodNameList.ProtoReflect.Descriptor instead.
func (*MethodNameList) Descriptor() ([]byte, []int) {
	return file_internal_extensions_extension_proto_rawDescGZIP(), []int{3}
}

func (x *MethodNameList) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          [][]byte               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_internal_extensions_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_internal_extensions_extension_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // üres ha nincs hiba
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_internal_extensions_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_internal_extensions_extension_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_extensions_extension_proto protoreflect.FileDescriptor

const file_internal_extensions_extension_proto_rawDesc = "" +
	"\n" +
	"#internal/extensions/extension.proto\x12\n" +
	"extensions\"\a\n" +
	"\x05Empty\"4\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"B\n" +
	"\fVariableList\x122\n" +
	"\tvariables\x18\x01 \x03(\v2\x14.extensions.VariableR\tvariables\"*\n" +
	"\x0eMethodNameList\x12\x18\n" +
	"\amethods\x18\x01 \x03(\tR\amethods\"8\n" +
	"\x0eExecuteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\fR\x04args\"?\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xda\x01\n" +
	"\x10ExtensionManager\x12;\n" +
	"\fGetVariables\x12\x11.extensions.Empty\x1a\x18.extensions.VariableList\x12?\n" +
	"\x0eGetMethodNames\x12\x11.extensions.Empty\x1a\x1a.extensions.MethodNameList\x12H\n" +
	"\rExecuteMethod\x12\x1a.extensions.ExecuteRequest\x1a\x1b.extensions.ExecuteResponseB0Z.github.com/flarelang/flare/internal/extensionsb\x06proto3"

var (
	file_internal_extensions_extension_proto_rawDescOnce sync.Once
	file_internal_extensions_extension_proto_rawDescData []byte
)

func file_internal_extensions_extension_proto_rawDescGZIP() []byte {
	file_internal_extensions_extension_proto_rawDescOnce.Do(func() {
		file_internal_extensions_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_extensions_extension_proto_rawDesc), len(file_internal_extensions_extension_proto_rawDesc)))
	})
	return file_internal_extensions_extension_proto_rawDescData
}

var file_internal_extensions_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_extensions_extension_proto_goTypes = []any{
	(*Empty)(nil),           // 0: extensions.Empty
	(*Variable)(nil),        // 1: extensions.Variable
	(*VariableList)(nil),    // 2: extensions.VariableList
	(*MethodNameList)(nil),  // 3: extensions.MethodNameList
	(*ExecuteRequest)(nil),  // 4: extensions.ExecuteRequest
	(*ExecuteResponse)(nil), // 5: extensions.ExecuteResponse
}
var file_internal_extensions_extension_proto_depIdxs = []int32{
	1, // 0: extensions.VariableList.variables:type_name -> extensions.Variable
	0, // 1: extensions.ExtensionManager.GetVariables:input_type -> extensions.Empty
	0, // 2: extensions.ExtensionManager.GetMethodNames:input_type -> extensions.Empty
	4, // 3: extensions.ExtensionManager.ExecuteMethod:input_type -> extensions.ExecuteRequest
	2, // 4: extensions.ExtensionManager.GetVariables:output_type -> extensions.VariableList
	3, // 5: extensions.ExtensionManager.GetMethodNames:output_type -> extensions.MethodNameList
	5, // 6: extensions.ExtensionManager.ExecuteMethod:output_type -> extensions.ExecuteResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_extensions_extension_proto_init() }
func file_internal_extensions_extension_proto_init() {
	if File_internal_extensions_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_extensions_extension_proto_rawDesc), len(file_internal_extensions_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_extensions_extension_proto_goTypes,
		DependencyIndexes: file_internal_extensions_extension_proto_depIdxs,
		MessageInfos:      file_internal_extensions_extension_proto_msgTypes,
	}.Build()
	File_internal_extensions_extension_proto = out.File
	file_internal_extensions_extension_proto_goTypes = nil
	file_internal_extensions_extension_proto_depIdxs = nil
}
